language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - REPO_NAME=cakephp-ftp
    - PLUGIN_NAME=Ftp
    - REQUIRE=""

  matrix:
    - DB=mysql CAKE_VERSION=2.9
    - DB=mysql CAKE_VERSION=2.10

matrix:
  include:
    - php: 7.0
      env:
        - DB=mysql CAKE_VERSION=2.8 COVERALLS=1

before_script:
  - composer selfupdate
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - ../travis/before_script.sh
  - cd ../cakephp/app
  - ln -s ~/.composer/vendor/phpseclib ../vendors/phpseclib
  - echo "Configure::write('Security.salt', 'AycG93b0qyJfIxfs2guVoUubWwvniR2G0FgaC9mi');" >> Config/bootstrap.php
  - echo "Configure::write('Security.cipherSeed', '16659201697453542496749683615');" >> Config/bootstrap.php
  - cd ..

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
